name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Firebase API Keys
        run: |
          TARGET_FILE=./src/firebase.js
          sed -i "s|__VITE_API_KEY__|${{ secrets.VITE_API_KEY }}|g" $TARGET_FILE
          sed -i "s|__VITE_AUTH_DOMAIN__|${{ secrets.VITE_AUTH_DOMAIN }}|g" $TARGET_FILE
          sed -i "s|__VITE_DATABASE_URL__|${{ secrets.VITE_DATABASE_URL }}|g" $TARGET_FILE
          sed -i "s|__VITE_PROJECT_ID__|${{ secrets.VITE_PROJECT_ID }}|g" $TARGET_FILE
          sed -i "s|__VITE_STORAGE_BUCKET__|${{ secrets.VITE_STORAGE_BUCKET }}|g" $TARGET_FILE
          sed -i "s|__VITE_MESSAGING_SENDER_ID__|${{ secrets.VITE_MESSAGING_SENDER_ID }}|g" $TARGET_FILE
          sed -i "s|__VITE_APP_ID__|${{ secrets.VITE_APP_ID }}|g" $TARGET_FILE
          sed -i "s|__VITE_MEASUREMENT_ID__|${{ secrets.VITE_MEASUREMENT_ID }}|g" $TARGET_FILE
      
      - name: Check file content after replacement
        run: cat ./src/firebase.js

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
